### ISSUE TITLE
Clarifications on rules direction meaning

### ISSUE THREAD

**Issue by bl17zar** [tommyod/Efficient-Apriori#15]
Hi, again. As I have already mentioned this is a very good quality package, and I have question concerning logic behind the algorithm. Maybe you could help on clarification of the following question.

For example I have the next rules produced by the Apriori algorithm :
```
[{eggs} -> {bacon}, {bacon} -> {eggs}]
```
Both with different ```confidence``` and ```support``` values. If I understand correctly the first rule means that people who first let the system know that they will buy eggs will mostly buy bacon as well with the  corresponding probability. And the second one means that people who first let the system know that they will buy bacon will also buy eggs with the corresponding probability.

So if I am not interested in the order people add items to their purchase how shall I interpret this result. Can I just sum the corresponding ```confidence``` and ```support``` and get rid of the directional arrow or it is forbidden?

Thanks in advance!

**Comment by tommyod** [comment]
The words [support, confidence, etc](https://en.wikipedia.org/wiki/Association_rule_learning#Useful_Concepts) are kind of stupid. It's just are-labeling of probabilities. Read the linked wikipedia page. In general you cannot add these probabilities.

- Confidence is conditional probability (as you described correctly).
- Support is probability of the itemset.

In your example, rules such as `{eggs} -> {bacon}` and `{bacon} -> {eggs}` should have the same confidence. It's just the probability that eggs and bacon appear together. 

*You you can take the confidence of either rule if you do not care about order, since the confidence should be equal.*

**Comment by bl17zar** [comment]
> In your example, rules such as {eggs} -> {bacon} and {bacon} -> {eggs} should have the same confidence. It's just the probability that eggs and bacon appear together.

> You you can take the confidence of either rule if you do not care about order, since the confidence should be equal.

I think you wanted to say that support will stay the same by meaning of what the support is. And I can confirm it with the results of running the algorithm. But I got the idea that confidence is not so important if we don't care about order. The main thing is the support which tells us the probability of meeting this itemset in the dataset regardles of order of items in itemset.

**Comment by tommyod** [comment]
You are exactly right :+1:
