### ISSUE TITLE
Could Polars increase memory usage and speed?

### ISSUE THREAD

**Issue by Et9797** [tommyod/Efficient-Apriori#69]
Currently the algorithm requires converting pandas dataframes to lists of tuples for the algorithm the work, which aren't memory optimized compared to numpy arrays. The problem I've found when working with GBs of data is that it will quickly run out of memory on my local machine if I don't tune `min_confidence` and `min_support` to the right values my machine can handle. Could Polars potentially improve the speed and efficiency of this package?

From benchmarks Polars has shown to be extremely fast, even when processing 1,000,000,000+ rows on a local machine with just 8GBs of ram, while Pandas runs immediately out of memory if the data size exceeds the machines memory. https://h2oai.github.io/db-benchmark/

**Comment by tommyod** [comment]
The quick answer is: no, I don't think so.

> Could Polars potentially improve the speed and efficiency of this package?

How _exactly_ do you envision using Polars to increase the speed?

The polars data structures are optimized for dataframe operations. The apriori algorithm cannot (to my knowledge) easily be expressed as dataframe operations. Just like many other algorithms.

Same with numpy arrays. They are optimized for array operations, but again the apriori algorithm cannot be expressed as array operations.

Open to suggestions and being proven wrong about this, but then please provide some concrete examples as to how you envision polars/numpy data structures using less memory or providing speedup within the context of the apriori algorithm.

**Comment by seanv507** [comment]
I believe polars/numpy memory structure is more memory efficient than python lists of tuples.

basically they achieve a memory optimisation because they assume a fixed type. a numpy array basically requires only the memory for the underlying data eg int32 requires 4 bytes per value. whereas a python list stores ?pointers to pyobjects with meta data for each object (rather than per array), and requires around 28 bytes

https://codebeez.nl/blogs/the-memory-footprint-of-your-python-application/ 

pandas (afaik) uses numpy as the backend storage (might be changing), so cannot support arrays of arrays well.
polars can store arrays in its columns ( ie a column has type array of int)
so I believe polars column of arrays of ints would be more memory efficient than a python list of tuples (of arbitrayry types).


I probably have a misunderstanding of the apriori algorithm, but I thought the fundamental operations 
can be represented as cross join within basket (across objects), group by object pairs, count and filter 

these are all optimised operations in polars.

**Comment by tommyod** [comment]
There are two statements here that are loosely related to performance: (1) memory and (2) runtime. 

When it comes to memory, a Python list is not as efficient as a numpy array of ints. This is a trivial observation, and might not be a good reason to rewrite code to use numpy, since the two data structures are optimized for different operations. When it comes to runtime, I stand by my previous comment: the apriori algorithm is probably not best expressed using tables: Python primitives are a good choice.

If anyone disagrees, then feel free to re-write the core of the algorithm and do a benchmark. The burden of proof is on you :) If the resulting code is both easier to reason about and faster, then I might merge a PR.

Of course, there is a slippery slope here: you can easily write a fast C++ or Rust implementation of the apriori algorithm if you truly need speed, then call that from Python. If you are willing to wrangle the algorithm into dataframe-space and express it as dataframe operations, you might as well go all the way? The purpose of this package is to provide a fast Python implementation with clean code and few dependencies, not to be state of the art in terms of speed. If you need that, then there already exists super fast C algorithms written by [Christian Borgelt](https://borgelt.net/software.html), who seems to have spent a good portion of his career on these algorithms.

All this being said I do not want to come across as negative, and encourage anyone to try to re-write for speed. As a fun project in a fork, or potentially as a PR that can be merged into this repository. I do not have time nor interest to re-write this package right now.

**Comment by Et9797** [comment]
> There are two statements here that are loosely related to performance: (1) memory and (2) runtime.
> 
> When it comes to memory, a Python list is not as efficient as a numpy array of ints. This is a trivial observation, and might not be a good reason to rewrite code to use numpy, since the two data structures are optimized for different operations. When it comes to runtime, I stand by my previous comment: the apriori algorithm is probably not best expressed using tables: Python primitives are a good choice.
> 
> If anyone disagrees, then feel free to re-write the core of the algorithm and do a benchmark. The burden of proof is on you :) If the resulting code is both easier to reason about and faster, then I might merge a PR.
> 
> Of course, there is a slippery slope here: you can easily write a fast C++ or Rust implementation of the apriori algorithm if you truly need speed, then call that from Python. If you are willing to wrangle the algorithm into dataframe-space and express it as dataframe operations, you might as well go all the way? The purpose of this package is to provide a fast Python implementation with clean code and few dependencies, not to be state of the art in terms of speed. If you need that, then there already exists super fast C algorithms written by [Christian Borgelt](https://borgelt.net/software.html), who seems to have spent a good portion of his career on these algorithms.
> 
> All this being said I do not want to come across as negative, and encourage anyone to try to re-write for speed. As a fun project in a fork, or potentially as a PR that can be merged into this repository. I do not have time nor interest to re-write this package right now.

@tommyod @seanv507 Coming back to this thread, since it is where this started for me (and for future readers who land here).

After opening this issue I took the "burden of proof is on you" seriously and built it myself. The result is now open source: ET-Miner (https://github.com/Et9797/ET-Miner). It began exactly as discussed here, as an attempt to express Apriori-style itemset mining in Polars with streaming, so the GBs-of-data case from my original post runs fine on a normal machine. It has since grown well beyond that: a Rust tier for sparse data, and GPU-accelerated mining (CUDA bitmap counting kernels, multi-GPU) for the largest workloads, in the 100M+ transaction range.

Two honest notes. @tommyod called it in his last comment: the dataframe formulation only carries you so far, and the bigger wins came from going "all the way" down the stack. And efficient-apriori is still part of the project: it serves as the correctness oracle in ET-Miner's test suite, so every result is verified against this package. Thanks for the library, and for the nudge.

If either of you is curious, feedback is very welcome.
